apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: clickhouse-storage-pvc
  name: clickhouse-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 11Gi