apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: clickhouse
  name: clickhouse
spec:
  ports:
    - name: "8123"
      port: 8123
      targetPort: 8123
      nodePort: 31123
    - name: "9000"
      port: 9000
      targetPort: 9000
      nodePort: 31000
  type: NodePort
  selector:
    service: clickhouse
status:
  loadBalancer: {}