apiVersion: v1
data:
  otel-collector-config.yml: |
    receivers:
      fluentforward:
        endpoint: 0.0.0.0:24224
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      clickhouse:
        endpoint: tcp://clickhouse:9000
        database: otel
        logs_table_name: otel_logs
        traces_table_name: otel_traces
        ttl: 720h
        timeout: 10s
        sending_queue:
          queue_size: 100
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s
    processors:
     batch:
       timeout: 5s
       send_batch_size: 100000
    service:
     pipelines:
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [clickhouse]
        traces:
         receivers: [otlp]
         processors: [batch]
         exporters: [clickhouse]
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: otelcollector
  name: otelcollector-cm0
